"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app -A    # Use -A for alias mode (recommended)
    python setup.py py2app       # Standalone mode (may crash with Python 3.13)
"""

from setuptools import setup

APP = ['gpg_gui.py']
DATA_FILES = [('', ['GpgGui.png'])]
OPTIONS = {
    'iconfile': '/Users/laurent/Code/gpg_gui/GpgGui.icns',
    'plist': {
        'CFBundleName': 'GpgGui',
        'CFBundleDisplayName': 'GPG GUI',
        'CFBundleVersion': '1.0.0',
        'CFBundleIdentifier': 'com.gpggui.app'
    },
    'argv_emulation': False,
    'semi_standalone': False,
    'site_packages': True
}

setup(
    name="GpgGui",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)
